# Generated by Django 5.2.1 on 2025-05-29 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('privacidade', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PUBLICO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livros_capas/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('data_nasc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LeituraClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A_LER', 'A Ler (Lista de Desejos)'), ('PROXIMO', 'Próximo a Ser Lido'), ('LENDO', 'Lendo Atualmente'), ('FINALIZADO', 'Finalizado')], max_length=15)),
                ('nota_media_clube', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.clube')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Reunião de Discussão', max_length=200)),
                ('data_horario', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('REMOTO', 'Remoto'), ('PRESENCIAL', 'Presencial')], default='REMOTO', max_length=15)),
                ('link_reuniao', models.URLField(blank=True, max_length=500, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('meta_tipo', models.CharField(blank=True, choices=[('CAPITULOS', 'Capítulos'), ('PAGINAS', 'Páginas')], max_length=15, null=True)),
                ('meta_quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('leitura_clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='inicial.leituraclube')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.clube')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClubeMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('MODERADOR', 'Moderador'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=10)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.clube')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'clube')},
            },
        ),
        migrations.AddField(
            model_name='clube',
            name='membros',
            field=models.ManyToManyField(related_name='clubes', through='inicial.ClubeMembro', to='inicial.usuario'),
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField()),
                ('is_ativa', models.BooleanField(default=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes', to='inicial.clube')),
                ('livros_opcoes', models.ManyToManyField(to='inicial.livro')),
            ],
        ),
        migrations.CreateModel(
            name='EstantePessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LENDO', 'Lendo'), ('LIDO', 'Lido'), ('ABANDONADO', 'Abandonado')], max_length=15)),
                ('nota_pessoal', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('favorito', models.BooleanField(default=False)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('progresso_paginas', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.clube')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'livro', 'clube')},
            },
        ),
        migrations.CreateModel(
            name='VotoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('livro_votado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.usuario')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='inicial.votacao')),
            ],
            options={
                'unique_together': {('votacao', 'usuario')},
            },
        ),
    ]
