# Generated by Django 5.2.1 on 2025-05-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='limite_membros',
            field=models.PositiveIntegerField(choices=[(10, 'Até 10 membros'), (20, 'Até 20 membros'), (50, 'Até 50 membros')], default=10),
        ),
        migrations.AlterField(
            model_name='clube',
            name='membros',
            field=models.ManyToManyField(related_name='clubes_participados', through='inicial.ClubeMembro', to='inicial.usuario'),
        ),
    ]
