# Generated by Django 5.2.1 on 2025-06-02 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0002_clube_limite_membros_alter_clube_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='capa_clube',
            field=models.ImageField(blank=True, null=True, upload_to='clubes_capas/'),
        ),
        migrations.AddField(
            model_name='clube',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
