# Generated by Django 5.2.1 on 2025-06-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0003_clube_capa_clube_clube_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
