# Generated by Django 5.2.1 on 2025-06-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0004_livro_isbn13'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='capa_recomendada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
