# Generated by Django 5.2.1 on 2025-07-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0005_clube_capa_recomendada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='leitura_clube',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='clube',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='inicial.clube'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reuniao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Detalhes, pauta ou o que será discutido na reunião.', null=True),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='leitura_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunioes_agendadas', to='inicial.leituraclube'),
        ),
    ]
