# Generated by Django 5.2.1 on 2025-08-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0006_remove_reuniao_leitura_clube_reuniao_clube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
