# Generated by Django 5.2.1 on 2025-08-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0007_usuario_auth_token_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
