# Generated by Django 5.2.1 on 2025-09-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0008_clube_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='tipo',
            field=models.CharField(choices=[('REMOTO', 'Remoto'), ('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido')], default='REMOTO', max_length=15),
        ),
    ]
