# Generated by Django 5.2.1 on 2025-09-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0009_alter_reuniao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='is_active',
        ),
        migrations.AddField(
            model_name='clube',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='clube',
            name='unique_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ID do Clube'),
        ),
        migrations.AddField(
            model_name='clubemembro',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='clubemembro',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='estantepessoal',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='estantepessoal',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='leituraclube',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='leituraclube',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='unique_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ID de Usuário'),
        ),
        migrations.AddField(
            model_name='votacao',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='votacao',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='votousuario',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='votousuario',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='clubemembro',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MODERADOR', 'Moderador'), ('MEMBRO', 'Membro'), ('PENDENTE', 'Pendente'), ('BANIDO', 'Banido')], default='MEMBRO', max_length=10),
        ),
    ]
