# Generated by Django 5.2.1 on 2025-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0010_remove_clube_is_active_clube_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/capas/', verbose_name='Foto de Capa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
