# Generated by Django 5.2.1 on 2025-09-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0011_usuario_bio_usuario_foto_capa_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bio'),
        ),
    ]
