# Generated by Django 5.2.1 on 2025-09-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0012_alter_clube_descricao_alter_usuario_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacao',
            name='titulo',
            field=models.CharField(default='Votação para Próximo Livro', max_length=50),
        ),
    ]
