# Generated by Django 5.2.1 on 2025-09-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0013_votacao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacao',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
