# Generated by Django 5.2.1 on 2025-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0014_alter_votacao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituraclube',
            name='status',
            field=models.CharField(choices=[('A_LER', 'Queremos Ler'), ('PROXIMO', 'Próximo a Ser Lido'), ('LENDO', 'Lendo Atualmente'), ('FINALIZADO', 'Finalizado')], max_length=15),
        ),
    ]
