# Generated by Django 5.2.1 on 2025-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0015_alter_leituraclube_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituraclube',
            name='status',
            field=models.CharField(choices=[('A_LER', 'Queremos Ler'), ('PROXIMO', 'Próximo a Ser Lido'), ('LENDO', 'Lendo Atualmente'), ('FINALIZADO', 'Finalizado'), ('ABANDONADO', 'Abandonado')], max_length=15),
        ),
    ]
