# Generated by Django 5.2.1 on 2025-10-02 17:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0016_alter_leituraclube_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituraclube',
            name='status',
            field=models.CharField(choices=[('A_LER', 'Queremos Ler'), ('LENDO', 'Lendo Atualmente'), ('FINALIZADO', 'Finalizado'), ('ABANDONADO', 'Abandonado')], max_length=15),
        ),
        migrations.CreateModel(
            name='AvaliacaoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('leitura_clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='inicial.leituraclube')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicial.usuario')),
            ],
            options={
                'unique_together': {('leitura_clube', 'usuario')},
            },
        ),
    ]
