# Generated by Django 5.2.1 on 2025-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0017_alter_leituraclube_status_avaliacaoleitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='termos_aceitos',
            field=models.BooleanField(default=False),
        ),
    ]
